// This file is generated by icon spritesheet generator

export const iconNames = [
	'arrow-left',
	'arrow-right',
	'avatar',
	'camera',
	'check',
	'clock',
	'cross-1',
	'dots-horizontal',
	'download',
	'envelope-closed',
	'exit',
	'file-text',
	'github-logo',
	'laptop',
	'link-2',
	'lock-closed',
	'lock-open-1',
	'magnifying-glass',
	'moon',
	'passkey',
	'pencil-1',
	'pencil-2',
	'plus',
	'question-mark-circled',
	'reset',
	'sun',
	'trash',
	'update',
] as const

export type IconName = (typeof iconNames)[number]
